modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
    modId = "gimmebroadcast"
    displayName = "GimmeBroadcast"
    version = "${modVersion}"
    side = "SERVER"
    description = "Restores UDP LAN broadcast (224.0.2.60:4445)."

[[dependencies.gimmebroadcast]]
    modId = "neoforge"
    mandatory = true
    versionRange = "[21.6,21.7)"
    ordering = "NONE"
    side = "BOTH"
